[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/about/css/*"
  to = "/css/:splat"
  status = 200
# force = true
