[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/:path/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/:path/img/*"
  to = "/img/:splat"
  status = 200
  
[[redirects]]
  from = "/:path/:title/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/:path/:title/img/*"
  to = "/img/:splat"
  status = 200    
  